branch-defaults:
  default:
    environment: Udagramdev-env
global:
  application_name: udagram-dev
  artiface: www/Archive.zip
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: null
  workspace_type: Application
